name: Deploy Mini-Postman

on:
  push:
    branches: [master]
    paths:
      - 'mini-postman/client/**'
      - 'mini-postman/server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # 1. Установка Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    # 2. Сборка клиентской части
    - name: Build Client
      run: |
        cd mini-postman/client
        npm ci
        npm run build
      env:
        VITE_API_BASE_URL: /api/mini-postman

    # 3. Установка зависимостей для сервера
    - name: Prepare Server
      run: |
        cd mini-postman/server
        npm ci --omit=dev

    # 4. Создание структуры для деплоя
    - name: Create Deployment Structure
      run: |
        # Создаём папку mini-postman на сервере
        mkdir -p deployment/mini-postman
        # Копируем клиентскую сборку (dist) и серверные файлы в нужные директории
        cp -r mini-postman/client/dist deployment/mini-postman/dist
        cp -r mini-postman/server deployment/mini-postman/server

    # 5. Деплой файлов на сервер
    - name: Deploy Files
      uses: appleboy/scp-action@v0.1.5
      with:
        host: 178.250.247.67
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "deployment/mini-postman/*"
        target: "/root/mini-postman/"
        rm: true
        overwrite: true

    # 6. Завершающие действия (перезапуск серверных процессов, если нужно)
