name: Deploy Mini-Postman

on:
  push:
    branches: [master]
    paths:
      - 'mini-postman/client/**'
      - 'mini-postman/server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # 1. Установка Node.js (если требуется для сервера)
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    # 2. Подготовка клиентской части (сборка)
    - name: Build Client
      run: |
        cd mini-postman/client
        npm ci
        npm run build
      env:
        VITE_API_BASE_URL: /api/mini-postman

    # 3. Подготовка серверной части (установка зависимостей)
    - name: Prepare Server
      run: |
        cd mini-postman/server
        npm ci --omit=dev

    # 4. Создание структуры для деплоя
    - name: Create Deployment Structure
      run: |
        # Создаём временную структуру для деплоя
        mkdir -p deployment
        # Копируем клиентскую сборку (dist) и серверные файлы
        cp -r mini-postman/client/dist/* deployment/
        cp -r mini-postman/server/* deployment/

    # 5. Деплой файлов на сервер
    - name: Deploy Files
      uses: appleboy/scp-action@v0.1.5
      with:
        host: 178.250.247.67
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "deployment/*"
        target: "/root/mini-postman/"
        rm: true
        overwrite: true

    # 6. Завершающие действия (перезапуск сервера или дополнительных сервисов не требуется)
