name: Deploy Mini Postman

on:
  push:
    branches: [ master ]
    paths:
      - 'mini-postman/client/**'
      - 'mini-postman/server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Build React app (Mini Postman)
      run: |
        cd mini-postman/client
        npm install
        npm run build
      env:
        NODE_OPTIONS: --openssl-legacy-provider

    - name: Prepare deployment artifacts
      run: |
        rm -rf deployment
        mkdir deployment
        cp -r mini-postman/client/dist deployment/
        cp -r mini-postman/server deployment/
        rm -rf deployment/server/node_modules

    - name: Validate SSH Key
      run: |
        if [ -z "$SSH_PRIVATE_KEY" ]; then
          echo "::error::SSH_PRIVATE_KEY secret is missing"
          exit 1
        else
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          ssh-keygen -lf key.pem
          rm key.pem
          echo "SSH key validation passed"
        fi
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Test SSH connection
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 178.250.247.67
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          echo "Connected to:"
          uname -a
          echo "Disk space:"
          df -h
        timeout: 30s

    - name: Deploy via SCP (Mini Postman)
      uses: appleboy/scp-action@v0.1.5
      with:
        host: 178.250.247.67
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "deployment/"
        target: "/root/mini-postman"
        rm: true
        overwrite: true
        strip_components: 1
        timeout: 2m

    - name: Install dependencies and restart mini-postman server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 178.250.247.67
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /root/mini-postman/server
          npm install --production
          pm2 delete mini-postman || true
          pm2 start app.js --name "mini-postman"
          pm2 save
          pm2 list
        timeout: 2m