name: Deploy SQL Explorer

on:
  push:
    branches: [ master ]
    paths:
      - 'sql-explorer/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Prepare deployment artifacts
      run: |
        rm -rf deployment
        mkdir -p deployment/client
        mkdir -p deployment/server/db
        cp -r sql-explorer/client/* deployment/client/
        cp -r sql-explorer/server/* deployment/server/
        cp sql-explorer/server/db/main.sqlite deployment/server/db/
        cp -r sql-explorer/demo_databases deployment/demo_databases
        cp sql-explorer/package.json deployment/
        cp sql-explorer/package-lock.json deployment/
        rm -rf deployment/server/node_modules

    - name: Validate SSH Key
      run: |
        echo "$SSH_PRIVATE_KEY" > key.pem
        chmod 600 key.pem
        ssh-keygen -lf key.pem
        rm key.pem
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy via SCP
      uses: appleboy/scp-action@v0.1.5
      with:
        host: 178.250.247.67
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "deployment/"
        target: "/root/sql-explorer"
        rm: true
        overwrite: true
        strip_components: 1
        timeout: 2m

    - name: Install dependencies, import DB, and restart server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 178.250.247.67
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /root/sql-explorer
          npm install --production

          echo "Importing MySQL demo database..."
          mysql -u root -e "DROP DATABASE IF EXISTS learning_db; CREATE DATABASE learning_db;"
          mysql -u root learning_db < demo_databases/learning_db/learning_db.sql

          echo "Restarting SQL Explorer with PM2..."
          pm2 delete sql-explorer || true
          pm2 start server/server.js --name "sql-explorer"
          pm2 save
          pm2 list