name: Deploy Mini-Postman

on:
  push:
    branches: [master]
    paths:
      - 'mini-postman/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Шаг 1. Сборка клиента (Vite)
    - name: Build Client
      run: |
        cd mini-postman/client
        npm ci
        npm run build
      env:
        VITE_API_BASE_URL: /api/mini-postman

    # Шаг 2. Подготовка сервера
    - name: Prepare Server
      run: |
        cd mini-postman/server
        npm ci --production
        # Копируем .env если есть
        [ -f .env.production ] && cp .env.production .env || echo "No .env.production"

    # Шаг 3. Создание артефактов
    - name: Create Artifacts
      run: |
        mkdir -p deployment
        # Клиент (сборка)
        cp -r mini-postman/client/dist deployment/client
        # Сервер (без node_modules)
        cp -r mini-postman/server deployment/
        rm -rf deployment/server/node_modules

    # Шаг 4. Деплой
    - name: Deploy
      uses: appleboy/scp-action@v0.1.5
      with:
        host: 178.250.247.67
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "deployment/"
        target: "/root/mini-postman/"
        rm: true
        overwrite: true

    # Шаг 5. Настройка сервера
    - name: Setup Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 178.250.247.67
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Установка зависимостей
          cd /root/mini-postman/server
          npm install --production

          # PM2
          pm2 delete mini-postman || true
          pm2 start app.js --name "mini-postman" --update-env
          pm2 save

          # Nginx
          sudo bash -c 'cat > /etc/nginx/conf.d/mini-postman.conf <<EOF
          location /mini-postman {
              alias /root/mini-postman/client;
              try_files \$uri /index.html;
          }

          location /api/mini-postman {
              proxy_pass http://localhost:3334;
              proxy_set_header Host \$host;
          }
          EOF'

          sudo nginx -t && sudo systemctl restart nginx